### ISSUE TITLE
invalid URL in dockerfile

### ISSUE THREAD

**Issue by enriko-riba** [collabnix/neo4j-docker-extension#1]
double `https://` in:
 "com.docker.extension.additional-urls='[{"title":"GitHub","url":"**_https://https:_**//github.com/collabnix/neo4j-docker-extension/"}]'"

**Comment by ajeetraina** [comment]
Thanks for reporting. I have fixed it. @enriko-riba

**Comment by certara-kklein** [comment]
Hi, I'm trying to sign in using neo4j/neo4j but I'm getting:

Neo.ClientError.Security.AuthenticationRateLimit: The client has provided incorrect authentication details too many times in a row.
